### ISSUE TITLE
Kleurgebruik

### ISSUE THREAD

**Issue by RayanSp** [Sascha-davidson/connect-your-tribe-squad-page#3]
Maak de donker blauwe kleuren iets lichter, met de zwarte text kleur is het nogal moeilijk om te lezen. 

<img width="167" alt="Schermafbeelding 2023-02-17 om 10 24 23" src="https://user-images.githubusercontent.com/112861069/219604208-a6560680-c5e1-4aed-b6dc-1d2a43e86202.png">

**Comment by Sascha-Davidson** [comment]
is niet meer relevant
