### ISSUE TITLE
HTML checker error 

### ISSUE THREAD

**Issue by mcphendriks** [Sascha-davidson/connect-your-tribe-squad-page#6]
HTML validate
<img width="200" alt="Screenshot 2023-02-23 at 14 27 53" src="https://user-images.githubusercontent.com/106346778/220920180-e71a8c1e-4767-4e41-ad4f-a2dcd690c831.png">

**Comment by Sascha-Davidson** [comment]
Ik kan niets aan deze errors doen. Het is afhankelijk hoe mensen hun api hebben ingevuld
